spring:
  application:
    name: order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demotest?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  profiles:
    active: dev
#mybatis:
#  mapper-locations: classpath:com/example/servicepayment9001/mapper/xml/*.xml
#  type-aliases-package: com.atguigu.springcloud.entities


server:
  port: 8001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  #\u96C6\u7FA4\u7248
  instance:
    instance-id: order8001
    prefer-ip-address: true
    #lease-renewal-interval-in-seconds: 1
    #lease-expiration-duration-in-seconds: 2

# 设置feign 客户端超时时间（openFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

#logging.level.root=INFO
#mybatis\u65E5\u5FD7
#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  mapper-locations: classpath*:com/example/serviceorder8001/mapper/xml/*.xml
feign:
  hystrix:
    enabled: true

#开启feign日志
#logging:
#  level:
    #feign日志以什么级别监控哪个接口
#   com.example.serviceorder8001.client.PaymentService: debug