spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demotest?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  profiles:
    active: dev
#mybatis:
#  mapper-locations: classpath:com/example/servicepayment9001/mapper/xml/*.xml
#  type-aliases-package: com.atguigu.springcloud.entities


server:
  port: 9001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  #\u96C6\u7FA4\u7248
  instance:
    instance-id: payment9001
    prefer-ip-address: true
    #lease-renewal-interval-in-seconds: 1
    #lease-expiration-duration-in-seconds: 2



#logging.level.root=INFO
#mybatis\u65E5\u5FD7
#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  mapper-locations: classpath*:com/example/servicepayment9001/mapper/xml/*.xml
